name: CI

on:
  push:
    branches:
    - main
    - feat/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Jimver/cuda-toolkit@v0.2.17
      id: cuda-toolkit
      with:
        cuda: '12.5.0'
    - name: make
      run: cd src; make

